version: '2'

networks:
  personal:
    driver: bridge
    # external:
    #   name: srv_personal

services:
  app: 
    build: .
    restart: on-failure
    networks:
      - personal
    ports:
      - 3000:3000 # local dev
    volumes:
      - ./dist:/app/dist
      - ./data:/app/data
      - ./app:/app/app
