version: '2'

networks:
  personal:
    # driver: bridge
    external:
      name: srv_personal

services:
  app: 
    build: .
    restart: on-failure
    networks:
      - personal
    ports:
      - 3000 #:3000 # local dev
    environment:
      - LETSENCRYPT_HOST=cm_viewer.karel-kroeze.nl
      - LETSENCRYPT_EMAIL=karel.kroeze@gmail.com
      - VIRTUAL_HOST=cm_viewer.karel-kroeze.nl
      - VIRTUAL_PORT=3000
